version: '3.8'

services:
  kafka:
    image: krisssssssss/kafka
    ports:
      - "9092:9092"

  kafka_backend:
    build:
      context: ./demo
    image: krisssssssss/kafka_backend
    ports:
      - "${PORT}:8080"
    env_file:
      - .env

  angular_frontend:
    build:
      context: ./frontend
    image: krisssssssss/angular_frontend
    ports:
      - "${FRONTEND_PORT:-4400}:4400"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
