version: '3.8'

services:
  app:
    build:
      context: ./demo
    image: test_kafka
    ports:
      - "${PORT}:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    image: angular_frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    env_file:
      - .env

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
