apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-backend
  labels:
    app: kafka-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-backend
  template:
    metadata:
      labels:
        app: kafka-backend
    spec:
      containers:
        - name: kafka-backend
          image: krisssssssss/kafka_backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: kafka-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
